# Generated by Django 3.2.16 on 2025-01-14 21:09

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_subscription_unique_subscription'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(check=models.Q(('subscriber', django.db.models.expressions.F('creator')), _negated=True), name='users_subscription_no_selffollow'),
        ),
    ]
