# Generated by Django 3.2.16 on 2025-01-24 20:32

import django.core.validators
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_subscription_users_subscription_no_selffollow'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='users_subscription_no_selffollow',
        ),
        migrations.AlterField(
            model_name='fguser',
            name='avatar',
            field=models.ImageField(default='', upload_to='users/avatars', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='fguser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Имейл'),
        ),
        migrations.AlterField(
            model_name='fguser',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='fguser',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='fguser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(regex='^[\\w.@+-]+\\Z')], verbose_name='Имя пользователя'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(check=models.Q(('subscriber', django.db.models.expressions.F('creator')), _negated=True), name='users_no_selffollow'),
        ),
    ]
