version: '3.3'

volumes:
  pg_data:
  media:
    name: media
  static:

services:
  db:
    image: postgres:13.10
    container_name: foodgram-db
    env_file: ../backend/.env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: ${DOCKER_USERNAME}/foodgram_backend
    container_name: foodgram-back
    env_file: ../backend/.env
    volumes: 
      - media:/app/foodgram_backend/media
      - static:/backend_static
  frontend:
    image: ${DOCKER_USERNAME}/foodgram_frontend
    container_name: foodgram-front
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    ports:
      - "7000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - media:/usr/share/nginx/media/
      - static:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
