# Generated by Django 3.2.16 on 2025-01-25 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Отметка "Избранное"', 'verbose_name_plural': 'Отметки "Избранное"'},
        ),
        migrations.AlterModelOptions(
            name='recipeshorturl',
            options={'verbose_name': 'Короткая ссылка', 'verbose_name_plural': 'Короткие ссылки'},
        ),
        migrations.CreateModel(
            name='ShoppingCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart_items', to='recipe.recipe', verbose_name='Рецепт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Элемент в корзине',
                'verbose_name_plural': 'Элементы в корзине',
            },
        ),
        migrations.AddConstraint(
            model_name='shoppingcartitem',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_recipe_in_users_cart'),
        ),
    ]
