# Generated by Django 3.2.16 on 2025-01-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0003_auto_20250115_1434'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shoppingcartitem',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_recipe_in_users_cart'),
        ),
    ]
