# User constants
EMAIL_MAX_LENGTH = 254
NAME_MAX_LENGTH = 150

# Ingredient constants
INGR_NAME_MAX_LENGTH = 128
INGR_UNIT_MAX_LENGTH = 64

TAG_MAX_LENGTH = 32

RECIPE_NAME_MAX_LENGTH = 256

SHORT_URL_MAX_LENGTH = 8

MAX_COOKING_TIME = 10000
MIN_COOKING_TIME = 1
